import SiteHeader from './components/SiteHeader'
import SiteFooter from './components/SiteFooter'

export default function HomePage(){return <main><SiteHeader/>
<section className="corp-hero"><div className="hero-overlay"/><div className="wrap corp-hero-grid"><div><p className="eyebrow">HEXA<span>ROOT</span> VENTURES · TEXAS</p><h1>Invest.<br/><em>Build.</em><br/>Scale.</h1><p className="hero-lead">A Texas-based venture and development company creating enduring value through real estate, infrastructure, partnerships, and future-focused businesses.</p><div className="hero-actions"><a className="button gold" href="/projects/hexafield">Explore HexaField ↗</a><a className="button ghost" href="/ventures">Our Ventures ↓</a></div></div><div className="hero-stat-panel"><div><strong>23+</strong><span>ACRES IN NORTH TEXAS</span></div><div><strong>04</strong><span>PLANNED CRICKET GROUNDS</span></div><div><strong>05</strong><span>FOUNDING PARTNERS</span></div></div></div></section>
<section className="intro-band"><div className="wrap two"><div><p className="eyebrow dark">ROOTED IN OPPORTUNITY</p><h2>Building ventures with <em>purpose.</em></h2></div><div><p>HexaRoot Ventures brings together opportunity, capital, land, partnerships, and execution to develop assets and businesses designed for long-term impact.</p><a className="text-link" href="/about">Discover HexaRoot ↗</a></div></div></section>
<section className="home-focus"><div className="wrap"><div className="section-title"><div><p className="eyebrow dark">WHAT WE BUILD</p><h2>Multiple verticals.<br/><em>One long-term vision.</em></h2></div></div><div className="focus-grid"><a href="/ventures#sports" className="focus-card focus-sports"><span>01</span><h3>Sports & Cricket<br/>Infrastructure</h3><p>Community-centered facilities and development opportunities across North Texas.</p></a><a href="/ventures#real-estate" className="focus-card focus-real"><span>02</span><small className="coming-soon">COMING SOON · 2027</small><h3>Real Estate &<br/>Land Development</h3><p>Strategic acquisition, planning, development, and long-term asset creation.</p></a><a href="/ventures#hospitality" className="focus-card focus-food"><span>03</span><small className="coming-soon">COMING SOON · 2027</small><h3>Food &<br/>Hospitality</h3><p>Future businesses built around quality experiences and disciplined operations.</p></a></div></div></section>
<section className="home-project"><div className="wrap project-callout"><div><p className="eyebrow">FEATURED DEVELOPMENT · NORTH TEXAS</p><h2>HexaField<br/><em>Development.</em></h2><p>23+ acres envisioned as a destination for cricket, recreation, community, and future development.</p><a className="button gold" href="/projects/hexafield">View Project ↗</a></div><div className="project-numbers"><div><b>23+</b><span>ACRES</span></div><div><b>04</b><span>GROUNDS</span></div><div><b>TX</b><span>NORTH TEXAS</span></div></div></div></section>
<section className="home-cta"><div className="wrap"><p className="eyebrow">LET'S BUILD WHAT'S NEXT</p><h2>Have an opportunity<br/><em>worth exploring?</em></h2><a className="button gold" href="/contact">Start a conversation ↗</a></div></section><SiteFooter/></main>}
